networks:
  model-network:
    driver: bridge

services:
  postgres:
    image: postgres:17.5
    container_name: postgresql-model
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - model-network

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: model-app
    depends_on:
      - postgres
    environment:
      TZ: America/Sao_Paulo
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      NAME_ADMIN: ${NAME_ADMIN}
      PASSWORD_ADMIN: ${PASSWORD_ADMIN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    networks:
      - model-network
    restart: always